# Generated by Django 2.0 on 2017-12-12 02:30

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_num_pages'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('django_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
